safedep/vet

internal/ui/progress.go, pkg/analyzer/cel_filter.go, pkg/analyzer/cel_filter_suite.go, pkg/models/models.go, pkg/scanner/callbacks.go, pkg/scanner/enrich.go, pkg/scanner/scanner.go, scan.go, test/scenarios/all.sh, test/scenarios/scenario-3-filter-fail-fast.sh
- Refactor scanner workflow to enable scanning per manifests instead of batching
- fix: Bug with tracker being marked as done
=> feat: Scan Manifest on Discovery

pkg/reporter/json_report.go
Hi
The `--report-json` flag in Vet generated a comprehensive json report file. However, it missed a field that was being displayed in the console output - the 'UPDATE TO' column data, that display what version the package should be upgraded to in order to mitigate the risk.
This PR, with a few lines of code, adds 'advices' field to the json report suggesting the alternate package version that the vulnerable package should be upgraded to.
```json
{
"package":
{
"ecosystem": "Maven",
"name": "com.nimbusds:nimbus-jose-jwt",
"version": "9.22"
},
"manifests":
[
"2de911f109118e4d"
],
"advices":
[
{
"target_alternate_package_version": "9.39.1"
}
],
"vulnerabilities":
[
{
"id": "GHSA-gvpg-vgmx-xg6w",
"title": "Denial of Service in Connect2id Nimbus JOSE+JWT",
"aliases":
[
"CVE-2023-52428"
]
}
], …
```
=> Add 'advices' field to the generated json report file

pkg/analyzer/lfp_npm.go, pkg/analyzer/lfp_npm_test.go
Fix for https://github.com/safedep/vet-action/issues/42
=> fix: Accept trusted URL base for LFP analyser

docs/docs/guides/code-analysis.md
Update tree-sitter parser link (https://tree-sitter.github.io/tree-sitter/) in Code Analysis documentation.
=> docs:  Update tree-sitter parser link for Code Analysis documentation

pkg/reporter/summary.go
This PR updates the column name in the `addRemediationAdviceTableRows` function from `Update To` to `Latest` for improved clarity and alignment with the backend data.
The term `Update To` could be misleading as it doesn't precisely represent the data provided by the backend. By renaming it to `Latest`, the table becomes clearer and more specific for users.
For more context, refer to the discussion in the related issue: [#292  - Unexpected Behavior When Scanning Non-Existing and Latest Versions of npm Packages](https://github.com/safedep/vet/issues/292#issuecomment-2513877159).
=> feat: Rename column "Update To" to "Latest" in remediation advice table

pkg/models/models.go, pkg/reporter/summary.go, pkg/scanner/enrich_insightsv2.go, test/scenarios/all.sh, test/scenarios/scenario-8-summary-report.sh
Show `slsa` provenance tag when available. This requires `--insights-v2` because thats the service that is provenance aware.
=> feat: Add SLSA tag in summary report when available

go.mod, pkg/analyzer/lfp_npm.go, pkg/analyzer/lfp_npm_test.go
=> Minor bugfix to handle cases where the package name doesn't resolve properly

pkg/reporter/markdown/emoji.go, pkg/reporter/markdown_summary.go
Improve markdown summary reporter to make it less verbose. Example: https://github.com/safedep/vet/issues/303#issuecomment-2603699774
=> fix: Improve markdown summary report to make malware analysis section collapsable

cmd/code/scan.go, pkg/storage/ent_sqlite.go
If user is doing - `vet code scan --db /tmp/a/b/c/dump/vet-test.db` and the intermediate dirs like `/tmp/a`, `/tmp/b` don't exists, vet would panic. This isn't handled by sqlite.
It is fixed using `os.MkdirAll` to ensure all intermediate paths exist.
Added `--exclude` mutli-string flag to skip misleading folders like `test-data/` which may contain dummy source code 
eg. 
```bash
vet code scan --db /tmp/vet-test.db --exclude test-data --exclude .venv
```
=> Exclude patterns option & ensure code DB path exists before preparing Code DB

cmd/cloud/login.go, cmd/cloud/main.go, cmd/cloud/quickstart.go, internal/ui/ui.go, scan.go
This PR adds support for SafeDep Cloud on-boarding using a quickstart command. It takes care of following cases
1. Authenticates user using device auth flow
2. Checks if user is on-boarded
3. If not on-boarded, start on-boarding using auto-generated tenant domain name, allowing user to customize
4. On-board user into SafeDep Cloud
5. Create API key for the tenant
6. Configure all credentials in local `vet` installation
This enables quick onboarding and getting started with SafeDep Cloud Services
=> feat: Add vet cloud quickstart command

go.mod
Removed the replace directive from go.mod file as it was causing a issue when running `go install..` command to download the vet binary as mentioned on the README.md file 
```
go install github.com/safedep/vet@latest
```
Below are two issues which discuss about the  error given if `replace` directive is present in `go.mod` file and someone used `go install ..` command to download the binary
https://github.com/golang/go/issues/44840
https://github.com/golang/go/issues/40276
After researching the the solution there where two options to solve this issue. 
1. Using the commit hash directly 
1.1 But in our case it is not possible the as `github.com/owenrumney/go-sarif/v2` already has a version tag release i.e `v2.3.1`. If we try to use `go get -u ...` command it will still not works as tags …
=> fix: remove replace directive from go.mod file

CONTRIBUTING.md
I tried to download gitleas using `asdf` but it didn't downloaded anything, later after some deep diving i find out we need to add `plugin` of particular tool to install that tool. 
```
asdf plugin add golang
asdf plugin add gitleaks
```
=> Add ASDF plugin installation steps to CONTRIBUTING.md

version.go
Fixes #385 
This solution is based on new go 1.24 feature: https://antonz.org/go-1-24/#main-modules-version
When app is build using `go install` then we will not be able to do `-ldflags`, hence our `version` will be `""`. In that case we will return version using `runtime/debugs`'s BuildInfo. 
Its value will be:
When the current commit matches a tagged version, the value is set to v<tag>[+dirty]:
```bash
v1.2.4
v1.2.4+dirty
```
When the current commit doesn't match a tagged version, the value is set to <pseudo>[+dirty], where pseudo consists of the latest tag, current date, and commit:
```bash
v1.2.3-0.20240620130020-daa7c0413123
v1.2.3-0.20240620130020-daa7c0413123+dirty
```
=> fix: missing version  on go install builds

Dockerfile
`debian:bullseye-slim` is very small, 80 MB, and current docker image is also near 80 MB.
This is critically needed as, Gitlab need image to `run as shell` for executing commands, like `vet scan` but current docker image being distroless does not have shell (sh).
=> fix: missing shell for using vet's image as environment

Dockerfile
> In previous pr, due to my mistake i didn't tested the new dockerfile locally. 
`nonroot` is not defined in debian, its only by default available in distroless images. So to adhere best practices, i have created a non-root user, this will fix the issue.
=> fix: use of default non-root user outside distroless images

version.go
i removed `os.Exit(1)` as `vet version` being successfully execured should exit with status code `0` which is default, that why no `os.exit(0)`.
=> fix: error code in vet version command

Dockerfile
Using `vet` container as `root` by default.
=> fix: container permission issue when creating report files

pkg/analyzer/malware.go, pkg/analyzer/malware_test.go, scan.go
Add support for configurable confidence level to fail in `vet` when it detects a malicious package.
Example:
```
./vet scan --purl $PURL --malware --malware-trust-tool-result --malware-analysis-min-confidence=MEDIUM
```
=> feat: Add support for malysis min confidence config

pkg/readers/github_org_reader.go, pkg/readers/github_org_reader_test.go, scan.go
The aim is to exclude specific repos like _**your-org/repo1**_ from being scanned when running, for example:
```
vet scan --github-org=https://github.com/your-org \
--github-org-exclude-repos="your-org/repo1,your-org/repo2"
```
- Added ExcludeRepos field to **_GithubOrgReaderConfig_**
- Registered **_--github-org-exclude-repos_** in scan.go
- Implemented _**isExcludedRepo()**_ helper
- Modified _**handleRepositoryBatch()**_ to skip excluded repos based on repo.GetFullName()
=> feat: add excludeRepos support to GithubOrgReader

pkg/readers/fixtures/duplicate-packages/requirements.txt, pkg/readers/lockfile_reader.go, pkg/readers/lockfile_reader_test.go, pkg/remediations/remediations.go, pkg/reporter/markdown_summary.go
=> Fixes duplicate & incorrect version in requirements.txt & empty Upgrade To Version Suggestion

test/scenarios/scenario-11-code-csvreport.sh
JSON report for this (doesn't have langchain critical vuln - `CVE-2024-7042`) - 
[vet-code.json](https://github.com/user-attachments/files/20878998/vet-code.json)
=> Fix e2e: scenario-11-code-csvreport.sh

main.go
Not visible in normal terminal, but found on `termshot`.
=> fix: extra space in ascii art

.github/workflows/goreleaser.yml
Removed subject generation step and updated provenance step to use native GitHub Attestation feature. 
Closes https://github.com/safedep/vet/issues/583
=> Refactor goreleaser workflow to use attest-build-provenance
