pkg/reporter/summary.go

This PR resolved the following issue
-  https://github.com/safedep/vet/issues/27

Fix-27 Duplicate findings in report summery

---

pkg/parser/pywheel.go
pkg/parser/pywheel_test.go

Add test cases for regexp based python wheel version parsing

Fix Bug in Python Wheel File Package Spec Parsing

---

README.md
pkg/common/purl/purl.go
pkg/common/purl/purl_test.go
pkg/common/utils/sbom/sbom.go
pkg/common/utils/sbom/sbom_test.go
pkg/parser/custom/sbom/spdx/spdx_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/readers/purl_reader.go
pkg/readers/purl_reader_test.go
scan.go

- Add support for RubyGems ecosystem
- Add support for PURL reader
- Add support for PURL scanning

feat: Add Support for RubyGems Ecosystem

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/container.yml
.github/workflows/dependency-review.yml
.github/workflows/golangci-lint.yml
.github/workflows/goreleaser.yml
.github/workflows/scorecard.yml
.github/workflows/secret_scan.yml
README.md
connect.go
internal/connect/github.go
main.go
pkg/parser/custom/sbom/spdx/spdx.go
pkg/readers/github_org_reader.go
pkg/readers/github_org_reader_test.go
pkg/readers/github_reader.go
pkg/readers/reader.go
pkg/scanner/callbacks.go
pkg/scanner/scanner.go
samples/filter-suites/fs-generic.yml
scan.go
test/e2e_github_org_reader_test.go

* Add support for Github Org scanning to enable #140

feat: Add Support for Github Organization Scanning

---

pkg/reporter/summary.go
scan.go

- fix: #180 provide explicit instruction to use vet community mode when auth verify fails
- fix: #180 Ensure version update is available before proposing in summary reporter

fix: Auth and Reporting Experience (#180)

---

go.mod
go.sum
pkg/common/purl/purl.go
pkg/common/utils/sbom/sbom_test.go
pkg/models/models.go
pkg/parser/fixtures/gha/.github/workflows/ci.yml
pkg/parser/gha_graph.go
pkg/parser/gha_graph_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

feat: Add initial support for scanning GitHub Actions

---

cmd/cloud/key.go
cmd/cloud/main.go
cmd/cloud/query.go
cmd/cloud/whoami.go
go.mod
go.sum
internal/ui/tabler.go
pkg/cloud/key.go

- **fix: UI rendering for cloud whoami command**
- **feat: Add table helper to ease table creation and persistence to file**
- **feat: Add api key list command**
- **feat: Add support to delete API key**

feat: Add Support for Cloud API Key Management

---

cmd/inspect/main.go
cmd/inspect/malware.go
go.mod
go.sum
internal/auth/auth.go
internal/auth/grpc.go
internal/ui/spinner.go
main.go

- **feat: Add support for malware analysis service integration**
- **feat: Update malware analysis command to poll for report**
- **fix: Spinner handling in malware analysis command**
- **fix: Malware analysis output table**
- **fix: Confidence string handling**

feat: Integrate with SafeDep Malware Analysis Service

---

pkg/reporter/csv.go
pkg/reporter/summary.go
test/scenarios/all.sh
test/scenarios/fixtures/code/requirements.txt
test/scenarios/fixtures/code/usage.py
test/scenarios/scenario-11-code-csvreport.sh

Added usage evidence in summary and CSV report

---

pkg/reporter/summary.go
query.go
scan.go

feat: Allow summary report to filter by usage evidence

---

.gitignore
pkg/models/models.go
pkg/parser/fixtures/uv.lock
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/uv_graph.go
pkg/parser/uv_graph_test.go

Implemented custom parser for uv.lock files

Feat/#374 support for scanning uv.lock files

---

pkg/reporter/callbacks.go
pkg/reporter/sync.go
scan.go

feat: progress bar in cloud report syncing

---

pkg/reporter/gitlab.go

feat: Improve Description and Solution for Vulnerabilities

---

pkg/models/models.go

Fixed incorrect dependencies provided by Package.GetDependencies

---

README.md

CDX reporting in readme

---

README.md

Docs: added instructions for container image scanning & and fix misc

---

agent/mcp.go
agent/ui.go
cmd/agent/common.go
cmd/agent/query.go
cmd/agent/query_prompt.md
cmd/server/mcp.go

- **Add package registry tool in vet MCP server**
- **Add /exit handling**

fix: Improve Agentic Query Prompt and Tools

---

pkg/readers/dir_reader.go
pkg/readers/lockfile_reader.go

This PR moves initialization of exclusion matcher to reader initialization.
cc: @Sahilb315

fix: Misc cleanup of exclusion matcher initialization

---

go.mod
go.sum
internal/analytics/event.go
pkg/models/models.go
pkg/readers/brew_reader.go
pkg/readers/brew_reader_test.go
scan.go

add support for generating sbom for homebrew installed packages

---

.github/workflows/publish-npm.yml

fix npm publish workflow to execute after goreleaser completion

---

.github/workflows/goreleaser.yml

Fix Attest build provenance failing

---

pkg/reporter/colors.go
pkg/reporter/colors_test.go
pkg/reporter/console.go
pkg/reporter/summary.go

- **fix: Color profile for console**
- **fix: Console color profile for dark mode**

fix: Console Color Profiles
